#!/bin/bash
set -o errexit

git pull

tx --traceback pull --force --all --source

./updatesources.sh

./jmdict-extract.py jmdict

./jmdict-extract.py kanjidic2

# check sources
for f in */*.pot; do
  msgfmt --check $f
done

# push translation source
tx push --source

# push translations and ignore errors
tx push --translations --skip

git commit -a -m "Automatic update with update_all"
git push origin master
