#!/bin/bash
set -o errexit

git pull

tx --traceback pull -a -f

./updatesources.sh

./jmdict-extract.py jmdict

./jmdict-extract.py kanjidic2

# push translation source
tx push -s

# push translations and ignore errors
tx push -t --skip

git commit -a -m "Automatic update with update_all"
git push origin master
