#!/bin/bash
set -o errexit

git pull

tx --traceback pull --force --all --source
git commit -a -m "Resources update from Transifex" 

./updatesources.sh

./jmdict-extract.py jmdict

./jmdict-extract.py kanjidic2

#git commit -a -m "Automatic update with update_all"

# check sources
for f in */*.pot; do
  msgfmt --check $f
done

# push translation source
#tx push --source

# push translations and ignore errors
#tx push --translations --skip

#git push origin master

